### ISSUE TITLE
Migrate project to terraform-routeros org

### ISSUE THREAD

**Issue by GNewbury1** [terraform-routeros/terraform-provider-routeros#130]
We should migrate this project to the terraform-routeros org to make sure it's not just in a single user's namespace.

Thoughts. @vaerh?

**Comment by raoulbhatia** [comment]
From an open source and collaboration perspective, I consider this is an excellent approach!

**Comment by vaerh** [comment]
I agree with this idea. Let's go!

**Comment by GNewbury1** [comment]
We have migrated to the terraform-routeros org! @vaerh , I have set you as an owner alongside me :)
