### ISSUE TITLE
routeros_wireguard_peer error while setting `persistent_keepalive`

### ISSUE THREAD

**Issue by javierbertoli** [terraform-routeros/terraform-provider-routeros#142]
**Describe the bug**
When setting the parameter `persistent_keepalive` in the `routeros_wireguard_peer` resource, applying the resource succeeds (the parameter is set) but errors with
```
│ Error: <nil> for 'persistent_keepalive' field
│ 
│   with routeros_interface_wireguard_peer.ros["server"],
│   on wireguard.tf line 8, in resource "routeros_interface_wireguard_peer" "ros":
│    8: resource "routeros_interface_wireguard_peer" "ros" {
```

Afterwards, all commands (`apply`,  `plan`) return the same error even if the value is set.
Same error is returned when importing the resource.

**To Reproduce**
```hcl
resource "routeros_interface_wireguard_peer" "ros" {
     allowed_address      = [ "1.2.3.4/32" ]
     comment              = "VPN"
     endpoint_address     = "5.6.7.8"
     endpoint_port        = 12345
     interface            = "vpn"
     persistent_keepalive = 25
     public_key           = "a...Z="
}
```

**Expected behavior**
No errors.

**Comment by vaerh** [comment]
The value type has been changed from numeric to string. At the end of the timeout, there should be a seconds symbol "25s".

**Comment by javierbertoli** [comment]
Can confirm it works like a charm! Thanks, @vaerh ! :smiley:
