### ISSUE TITLE
routeros_dns_record does not change resource type and data correctly after #158

### ISSUE THREAD

**Issue by javierbertoli** [terraform-routeros/terraform-provider-routeros#159]
**Describe the bug**
After #158,  when a DNS RR type is changed, the operation apparently *adds/changes* the new parameters but does not change (or delete) the rest of the resource data consistently, resulting in an inconsistent  resource that can't be updated, as it results again in the error described in #150

```
│ Error: PUT 'https://my.mk/rest/ip/dns/static' returned response code: 400, message: 'Bad Request', details: 'invalid value for argument address:
│     invalid value for argument ip
│     invalid value for argument ipv6'
│ 
│   with routeros_ip_dns_record.new_cname,
│   on dns.tf line 14, in resource "routeros_ip_dns_record" "new_cname":
│   14: resource "routeros_ip_dns_record" "ros" {
│ 
```

**To Reproduce**
1. Create an `A` record
```hcl
resource "routeros_ip_dns_record" "a_record" {
  name     = "a.local"
  type     = "A"
  address  = "111.222.333.444"
}
```
2. Apply
3. Change resource type to `CNAME`
```hcl
resource "routeros_ip_dns_record" "a_record" {
  name     = "a.local"
  type     = "CNAME"
  cname  = "some.fqdn"
}
```
4. Apply (will error)
```
╷
│ Error: PATCH 'https://my.mk/rest/ip/dns/static/*3' returned response code: 400, message: 'Bad Request', details: 'invalid value for argument address:
│     invalid value for argument ip
│     invalid value for argument ipv6'
│ 
│   with routeros_ip_dns_record.a_record,
│   on dns.tf line 14, in resource "routeros_dns_record" "a_record"":
│   14: resource "routeros_dns_record" "a_record" {
│ 
```
5. Check the resulting entry in the state file
```
$ tf  state show  'routeros_ip_dns_record.a_record'
# routeros_ip_dns_record.a_record:
resource "routeros_ip_dns_record" "a_record" {
    address  = "111.222.333.444"
    cname    = "some.fqdn"
    disabled = false
    dynamic  = false
    id       = "*3"
    name     = "a.local"
    ttl      = "1d"
    type     = "CNAME"
}
```

where it can be seen that the _type_ was changed, the _cname_ was added but the _address_ was not removed (as it should have been)

**Expected behavior**
The resource should be updated consistently, according to the resource type.

**Comment by vaerh** [comment]
Thanks, I missed this moment. Please test the release and I want to draw your attention to the fact that the **type** field is now mandatory.
And I don't know how you could add a resource with such an interesting address :) "111.222.333.444", I did not immediately understand the reason for the refusal to add the resource and after that I added a validator that this is actually an IP address.

**Comment by javierbertoli** [comment]
Thanks! It works ok now.

Re: "111.222.333.444" sorry, my bad :smile: .I usually use such notation (or www.xxx.yyy.zzz) to state that is an IP, and didn't pay much attention to the fact that it was invalid when describing the error. Glad to know you added an extra test for such things!

Thanks a lot!
