### ISSUE TITLE
routeros_ip_dns - new fields in 7.8

### ISSUE THREAD

**Issue by durandguru** [terraform-routeros/terraform-provider-routeros#169]
**Describe the bug**
In RouterOS 7.8 there are new fields on the dns server settings. Those fields are not visible in Winbox. Errors below.

**To Reproduce**
Run for example the following setting
resource "routeros_ip_dns" "dns-server" {
  allow_remote_requests = true
  servers               = "2606:4700:4700::1112,1.1.1.2,2606:4700:4700::1002,1.0.0.2"
}
Next plan warning messages about fields missing.

**Errors**

│ Warning: Field 'doh_max_concurrent_queries' not found in the schema
│
│   with routeros_ip_dns.dns-server,
│   on general.tf line 5, in resource "routeros_dns" "dns-server":
│    5: resource "routeros_ip_dns" "dns-server" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'doh_max_concurrent_queries': '50' ◁
╵
╷
│ Warning: Field 'doh_max_server_connections' not found in the schema
│
│   with routeros_ip_dns.dns-server,
│   on general.tf line 5, in resource "routeros_dns" "dns-server":
│    5: resource "routeros_ip_dns" "dns-server" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'doh_max_server_connections': '5' ◁
╵
╷
│ Warning: Field 'doh_timeout' not found in the schema
│
│   with routeros_ip_dns.dns-server,
│   on general.tf line 5, in resource "routeros_dns" "dns-server":
│    5: resource "routeros_ip_dns" "dns-server" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'doh_timeout': '5s' ◁

**Comment by vaerh** [comment]
I have prepared the fixes, please check it after the release.

**Comment by durandguru** [comment]
Works! Thanks.
