### ISSUE TITLE
disabled mangle not seen

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#175]
```hcl
resource "routeros_ip_firewall_mangle" "preroute_mark_conn_11" {
  chain               = "prerouting"
  in_interface        = "isp11"
  connection_state    = "new"
  action              = "mark-connection"
  new_connection_mark = "isp11_conn"
}
```

go Disable the rule on the router -> plan is empty

**Comment by vaerh** [comment]
I need some time to think about what to do about this behavior. Perhaps I should have written that the provider was built on the assumption of a single control point - only terraform.

**Comment by n0rad** [comment]
> Perhaps I should have written that the provider was built on the assumption of a single control point - only terraform.

**Comment by n0rad** [comment]
> Perhaps I should have written that the provider was built on the assumption of a single control point - only terraform.

Which is fair, but you know in case of emergency you could go to the mikrotik directly and disable some stuff, and then will be lost in the convergence.

Actually it's working ok as soon as you add the `disabled` flags to all rules so I did. but my guess is that it should be seen as enabled by default if the flag is not set.

**Comment by vaerh** [comment]
I agree, there needs to be some changes and a lot of testing, since this flag is included in almost all resources.
I also take pause for implementation!

**Comment by n0rad** [comment]
Tested on nat and mangle, working perfectly! Thx
