### ISSUE TITLE
Support for routing/tables

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#181]
Among the setup I have to do on my mikrotik, adding routing tables to support multiple ISP routing is missing in the provider.

That would be nice to implement it.

**Comment by vaerh** [comment]
The implementation is not complicated, but there is an unexpected behavior of the 'fib' property (in terms of TF provider operation). I have sent an email to Mikrotik technical support.

**Comment by vaerh** [comment]
Added in the release 1.3.9.
