### ISSUE TITLE
Support for routing/bgp 

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#183]
Among the setup I have to do on my mikrotik, I have to setup BGP connections (routing/bgp/connection) to allow cilium in my kubernetes cluster to advertise external available services. 

That would be great to implement it in the provider.

**Comment by vaerh** [comment]
Marked in the plan for the second phase. I need to add support for OpenVPN server, but free time as always is not enough.

**Comment by n0rad** [comment]
To follow the routeros resources path, I think resources should be named `routeros_routing_bgp_connection` and not `routeros_bgp_connection` no?

**Comment by vaerh** [comment]
If this name raises questions, you'd better fix it.
