### ISSUE TITLE
ip/route: dst_address should not be mandatory

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#184]
Currently `routeros_ip_route` requires `dst_address` to be set, but in some cases, routes must be set without it like for example in multi ISP failover scenario.

It should not be a mandatory field. 

```
╷
│ Error: Missing required argument
│
│   on ip_route.tf line 135, in resource "routeros_ip_route" "d2_rmark_isp22":
│  135: resource "routeros_ip_route" "d2_rmark_isp22" {
│
│ The argument "dst_address" is required, but no definition was found.
╵
```

**Comment by vaerh** [comment]
Please publish the configuration of your resource.

**Comment by n0rad** [comment]
```
resource "routeros_ip_route" "d2_rmark_isp22" {
  distance    = 2
  gateway     = "10.10.10.1"
  routing_table = "to_isp22"
  target_scope = 12
}
```

following mikrotik documentation at: https://help.mikrotik.com/docs/pages/viewpage.action?pageId=26476608

**Comment by vaerh** [comment]
The problem is fixed, but I want to warn you: the "dst_address" field will still be set to "0.0.0.0/0".

**Comment by n0rad** [comment]
Thx, you are awesome, I see that mikrotik keep it blank when not set through UI, but I suppose it's equal to `0.0.0.0/0`
