### ISSUE TITLE
Add possibility to enable the `Hardware Offload` on bridge ports

### ISSUE THREAD

**Issue by DenisShalaevSetronica** [terraform-routeros/terraform-provider-routeros#188]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to enable the `Hardware Offload` option when adding ports to bridge using the `routeros_interface_bridge_port` resource.

**Additional context**
Example of usage:
```
resource "routeros_interface_bridge_port" "bridge_port_vlan_10" {
  bridge    = "bridge"
  interface = "ether1"
  pvid      = "10"
  hw_offload = true
}
```

**Current behaviour**
> Error: Value for unconfigurable attribute
>
>   with routeros_interface_bridge_port.bridge_port_vlan_10,
>   on main.tf line 57, in resource "routeros_interface_bridge_port" "bridge_port_vlan_10":
>   57:   hw_offload = "true"
>
> Can't configure a value for "hw_offload": its value will be decided automatically based on the result of applying this configuration.

**Expected behavior**
Add port to bridge and enable `Hardware Offload` option.

**Comment by vaerh** [comment]
Hi Denis, the **hw_offload** property is read-only. Use the **hw** attribute.

![image](https://user-images.githubusercontent.com/64400271/234533452-38bcb88b-28a8-41fc-97c9-c036ccd65d66.png)

```hcl
resource "routeros_interface_bridge_port" "bridge_port" {
  bridge    = "bridge1"
  interface = "ether1"
  pvid      = "1"
  hw        = true
}
```

**Comment by DenisShalaevSetronica** [comment]
Thank you, @vaerh !
Looks need to clarify this option assignment in documentation.
![image](https://user-images.githubusercontent.com/28853435/234560308-0edc7aac-bc2e-40f4-b158-c322e1f06291.png)

**Comment by vaerh** [comment]
Done. The description will change after the next release.
