### ISSUE TITLE
wifiwave2 support

### ISSUE THREAD

**Issue by MagicMicky** [terraform-routeros/terraform-provider-routeros#204]
Hey, thanks a lot for your work so far, really happy to see a developed routeros terraform provider!

I've been using it to modify my new mikrotik setup (one router, one AP) and am missing one feature. I'd love to be able to configure wifiwave2, and potentially the new capsman associated to it through the provider. This would allow me to really setup 95% of my config through terraform which would be quite nice :)

Any thought of adding support for [wifiwave2](https://help.mikrotik.com/docs/display/ROS/WifiWave2)?

Thanks!

**Comment by vaerh** [comment]
Hmm, I can't promise that this functionality will be implemented soon. CAPsMAN has been drinking a lot of my blood :) I need to look more closely at how it is implemented by specific commands and if there are any new wonders from Mikrotik. 
I need a command script from you for research.
