### ISSUE TITLE
Support for veth interfaces

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#206]
Dns service on mikrotik is not that great, so I'm preparing to run a `coredns` container.
Waiting for #86, I'm setting up the network for this container using the provider but it's missing the veth resource.

That would be great to supporting declaring `veth` interface with the provider.

**Comment by vaerh** [comment]
We will implement support for veth, but there is still a problem with containers related to testing. Perhaps I will add support, but without test coverage.

**Comment by vaerh** [comment]
There is one important point, there is no documentation for **veth** by MT, because of this you have to be a beta tester.

**Comment by n0rad** [comment]
working ok!
