### ISSUE TITLE
Field 'comment' not found in the schema

### ISSUE THREAD

**Issue by stawii** [terraform-routeros/terraform-provider-routeros#213]
**Describe the bug**
Both `routeros_ip_addresses` and `routeros_ip_routes` data resources cannot parse comment field.

**To Reproduce**
Just use them, but make sure any of IP addresses has a comment.
```hcl
data "routeros_ip_addresses" "main" {}
```

**Expected behavior**
Comment field is returned in schema (or silently ignored).

**Additional context**

The message that pops up:
```
│ Warning: Field 'comment' not found in the schema
│
│   with data.routeros_ip_addresses.main,
│   on main.tf line 17, in data "routeros_ip_addresses" "main":
│   17: data "routeros_ip_addresses" "main" {}
│
│ [MikrotikResourceDataToTerraformDatasource] the field was lost during the Schema development: ▷
│ 'comment': 'router.internal' ◁
│
│ (and 2 more similar warnings elsewhere)
```

This issue raises another story / bug. Whenever new fields are added to API, Terraform will report it not found in the schema with WARNING log-level. This is fine for provider developer or debugging however I found this annoying as provider user. I suggest reduce visibility of this message or to provide a way to silence it down.

**Comment by stawii** [comment]
Even comment in code suggests it should be for devs only ;)
https://github.com/terraform-routeros/terraform-provider-routeros/blob/c7d9264cad81f19319074cd6a90a4c327020c750/routeros/mikrotik_serialize.go#L474

**Comment by vaerh** [comment]
And that means the comments work :) My respect to you for finding them! 
I'll be fixing that soon.
