### ISSUE TITLE
/interface/bridge/mlag

### ISSUE THREAD

**Issue by MarcSN311** [terraform-routeros/terraform-provider-routeros#268]
There does not seem to be a way to configure mlag. The mlag ID field on a bond is present, but the bridge config can not be done.
Would be great if that could be implemented.

**Comment by vaerh** [comment]
What ROS version are you using?

**Comment by MarcSN311** [comment]
I am currently running 7.10, but the Feature was introduced in 7.1.0

**Comment by vaerh** [comment]
Hmm, CHR (Virtual Router v7.10) doesn't have that section

![изображение](https://github.com/terraform-routeros/terraform-provider-routeros/assets/64400271/bcd23b4a-393e-4035-8108-d8e884cc816b)

**Comment by vaerh** [comment]
@MarcSN311 Can you post a screenshot of that section of your router?

**Comment by tofkamp** [comment]
I use ROS 7.11.2. Make sure the slave ports are NOT part of any bridge.
A MLAG bond is created by "/interface/bonding add name=bond1 slaves=ether4,ether5 " which is present in this module. 
Add it to the bridge "/interface/bridge/port add bridge=bridge interface=bond1" (PVID is not required, resource demands it), also present in this terraform provider,
Add some VLAN's to the port in the bridge: /interface/bridge/vlan add bridge=bridge tagged=bond1 vlan-ids=10,20
This is also available.

Summary: the slave-ports are replaced by one port on the bridge with the name of the bonding. The slave-ports are not used anymore, unless you removed the bond.

**Comment by MarcSN311** [comment]
@vaerh 
GUI:
![grafik](https://github.com/terraform-routeros/terraform-provider-routeros/assets/12860202/4389287c-79f9-4057-b592-2af6a0ac91b2)

CLI:
![grafik](https://github.com/terraform-routeros/terraform-provider-routeros/assets/12860202/d4fc9657-68b0-498f-84c8-03e3f5d33c32)

Docs:
https://help.mikrotik.com/docs/display/ROS/Multi-chassis+Link+Aggregation+Group

**Comment by vaerh** [comment]
It is logical enough that in the case of linking several physical devices, this functionality is absent on a cloud router.
@MarcSN311 Can you publish the output of the REST?
```curl -kX POST -u user:password https://router-ip/rest/interface/bridge/mlag/print```

**Comment by vaerh** [comment]
@tofkamp 
Of course, within a single bridge, all aggregated ports will appear as a single logical port. Another thing is that I do not have this functionality in CHR in versions 7.10 and 7.11.2.

**Comment by MarcSN311** [comment]
@vaerh I am pretty sure that this is a hardware accelerated feature of the switch chip. I would assume that is the reason it is not present on a virtual router, because there is no switch chip.

I will post the output when I come back from work.

**Comment by MarcSN311** [comment]
Output is
`[{"bridge":"bridge1","peer-port":"stack-link"}]`
bridge1 is mz bridge (obviously) and stack-link is a bond.

**Comment by vaerh** [comment]
Thanks. I will add the resource soon, but you will be required to test it as I don't have a free router at hand.
