### ISSUE TITLE
how to access settings in /interface/ethernet/switch?

### ISSUE THREAD

**Issue by vaerh** [terraform-routeros/terraform-provider-routeros#285]
### Discussed in https://github.com/orgs/terraform-routeros/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **cbc02009** October 30, 2023</sup>
I'm setting up some switches running routerOS. When I manually configure them I have to set
```
/interface ethernet switch
set 0 l3-hw-offloading=yes
```
How do I achieve similar with this terraform provider?</div>

**Comment by tofkamp** [comment]
I don't know what kind of switch you have, but I do it this way:
```
resource "routeros_interface_bridge" "bridge" {
  name           = "bridge"
  vlan_filtering = true
}

resource "routeros_interface_bridge_port" "access_port" {
  pvid              = 10
  interface         = "ether2"
  bridge            = routeros_interface_bridge.bridge.name
  disabled          = false
  ingress_filtering = true
  frame_types       = "admit-only-untagged-and-priority-tagged"
  hw                = true
  comment           = "Access to server1"
  depends_on        = [routeros_interface_bridge.bridge]
}

resource "routeros_interface_bridge_vlan" "access_vlans" {
    vlan_ids = 10
    bridge   = routeros_interface_bridge.bridge.name
    comment = "Access to server1"
    untagged = "ether2"
    depends_on  = [routeros_interface_bridge.bridge]
}
```
I create a bridge, with a vlan. On that bridge I create a interface with that vlan. I enable hardware offloading with the option **hw=true**
https://registry.terraform.io/providers/terraform-routeros/routeros/latest/docs/resources/interface_bridge_port

**Comment by vaerh** [comment]
I don't know the model of the switch the discussion author has, but on my MT this option looks like this:

![image](https://github.com/terraform-routeros/terraform-provider-routeros/assets/64400271/2822234f-504e-4e2e-80a7-1df2c55b256f)
