### ISSUE TITLE
Data source to list DHCP leases

### ISSUE THREAD

**Issue by leijonatm** [terraform-routeros/terraform-provider-routeros#316]
**Is your feature request related to a problem? Please describe.**
Not actually a problem but "nice to have" a list of DHCP leases from the mikrotik server

**Describe the solution you'd like**
It would be nice if we could have a data source reporting all DHCP leases of the mikrotik device

Thanks

**Comment by leijonatm** [comment]
Great, thanks a bunch!!!

**Comment by vaerh** [comment]
Please test it!

**Comment by leijonatm** [comment]
I can confirm I get a list of the IPs the dhcp server has granted. Thanks again

Εστάλη από Outlook για iOS<https://aka.ms/o0ukef>
________________________________
Από: vaerh ***@***.***>
Στάλθηκε: Friday, December 15, 2023 8:39:02 PM
Προς: terraform-routeros/terraform-provider-routeros ***@***.***>
Κοιν.: leijonatm ***@***.***>; Author ***@***.***>
Θέμα: Re: [terraform-routeros/terraform-provider-routeros] Data source to list DHCP leases (Issue #316)


Please test it!

**Comment by leijonatm** [comment]
Hello @vaerh, 
I have the following block 
```
data "routeros_ip_dhcp_server_leases" "lease" {
  filter = {
    mac_address = data.netbox_device_interfaces.device_interface.interfaces[0].mac_address
  }
} 
```

and seems like the filter is not working . I get the following reply

```
lease = {
  "___id___" = tonumber(null)
  "___path___" = tostring(null)
  "data" = tolist([])
  "filter" = tomap({
    "mac_address" = "5C:ED:8C:3B:FE:64"
  })
  "id" = "terraform-20240111114359129200000001"
}
```
If I remove the filter I get the data fine and also if I search for the MAC address directly I see empty list. Could it be that the filter is not working ?

**Comment by vaerh** [comment]
@leijonatm 
You have got an exemplary error. Filter parameters are specified in MT notation (with dashes instead of underscores), but to prevent others from having such problems I added automatic conversion to the correct format. Please test it after the release.

**Comment by leijonatm** [comment]
It works like a charm. Thanks again !
