### ISSUE TITLE
data routeros_ip_service

### ISSUE THREAD

**Issue by OJFord** [terraform-routeros/terraform-provider-routeros#391]
**Is your feature request related to a problem? Please describe.**
I want to disable all IP services except those I have `local.services` configuration for.

**Describe the solution you'd like**
With a data source for ` GET /rest/ip/service`, I could `for_each` the result and exclude the service(s) I want to configure, and easily disable them all without hardcoding a list.

**Additional context**
For other use cases, and as is typical for such a data source, it would be good if it were filterable. On VRF or disabled attrs, would be the most obviously useful.

**Comment by vaerh** [comment]
I can only offer to create a data source for `routeros_ip_service`, so that the existing resources can be processed by terraform in a loop.
All data sources support the `filter` attribute, which can be used to filter a set of incoming values. 
The content of the filter is a map that can be filled with any field names.
``` hcl
data "routeros_firewall" "fw" {
  rules {
    filter = {
      chain = "input"
      comment = "rule_2"
    }
  }
}
```

**Comment by OJFord** [comment]
Yes that's exactly what I was hoping/imagining, sorry that wasn't clear.

I might get around to looking into it myself if that would be welcome.

Thanks!

**Comment by vaerh** [comment]
Of course, welcome!
Look at the code of the data sources, it is the same type except for the schema.
There is also a prototype code generator for this:
https://github.com/terraform-routeros/terraform-provider-routeros/issues/278#issuecomment-1793697181
