### ISSUE TITLE
Feature: make routeros_wifi `default_name` to behave like routeros_interface_ethernet `factory_name` 

### ISSUE THREAD

**Issue by zelitomas** [terraform-routeros/terraform-provider-routeros#403]
**Is your feature request related to a problem? Please describe.**
If you try to manage physical WiFi interface naively, i. e. by adding a `resource "routeros_wifi" "master" { name="wifi1", [...] }` block, you'll run into following error:
```
routeros_wifi.master["wifi1"]: Creating...
│ Error: PUT 'https://10.66.0.2/rest/interface/wifi' returned response code: 400, message: 'Bad Request', details: 'failure: already have interface with such name'
│ 
│   with module.cap1.routeros_wifi.master["wifi1"],
│   on cap/wifi.tf line 33, in resource "routeros_wifi" "master":
│   33: resource "routeros_wifi" "master" {
```
You can import your existing resource by finding out its ID and running `terraform import routeros_wifi.master *5` for every interface, but this can become very tedious, especially when trying to manage multiple APs as modules.

**Describe the solution you'd like**
I would like to configure physical Wifi interfaces the same way as Ethernet interfaces, e. g. without importing them first. 
It could work by utilizing `default_name` to work the same way as `factory_name` does in `routeros_interface_ethernet`, so that if you used following configuration, it would be linked to the correct interface.

```
resource "routeros_wifi" "master" { 
  name="wifi1"
  default_name="wifi1"
  [...]
}
```

**Additional context**

**Comment by dokmic** [comment]
Hey @zelitomas,

Thanks for bringing this one here.
I intentionally implemented it like that as it's not like the ethernet interfaces that cannot be created dynamically. The slave wifi interfaces can be added dynamically, and because of that, behavior cannot be the same as in `routeros_interface_ethernet`.

Terraform provides a declarative way to manage your infrastructure, and its state should be the only source of truth. If there is already a remote resource, then it should be explicitly synchronized by importing it.

**Comment by vaerh** [comment]
I don't want to interfere in your dialog, Michael, as the author has a full picture of the implemented functionality. At the same time I agree that it is necessary to know and use the current state of resources outside TF. Of course importing resources adds a bit of manual work, but I hope that the scale of your network will allow you to do it once.

**Comment by zelitomas** [comment]
Hello Michael,

first and foremost - thank you for your amazing work on the provider.

I agree with you that for slave interfaces the `routeros_interface_ethernet`s behavior doesn't make too much sense, but I would still argue that master wifi interface would deserve the same behavior as its ethernet counterpart. After all, just like like with ethernet interfaces, RouterOS doesn't allow you to create (or remove) them, and so only way how it can be managed is by importing.

Would it maybe be possible to have different behavior for master and slave wifi interfaces? Maybe splitting them into two resource types (after all - they even differ in properties you can set on them)? Or creating a synthetic `factory_name` attribute that would be 
null for slave interfaces and equal to `default_name` for masters, so that you could have current behavior for resources that can be created dynamically, and `ethernet`-like behavior for interfaces that can't?

If that isn't possible, would it at least be possible to simplify the import, so that you don't need to make a round trip to ROS just to find out which ids it has assigned to the interfaces? 

Maybe allowing to import with the name, as it is unique enough for the import to complete, and ROS prevents you from creating 2 interfaces with the same name? (`terraform import routeros_wifi.master wifi1`)

Thanks again for your great work.
Tomáš

**Comment by vaerh** [comment]
@zelitomas 
Please check if your request is implemented correctly after release  (I don't have any equipment with Wave2 enabled).
Description of use in the source code
[#414 ](https://github.com/terraform-routeros/terraform-provider-routeros/pull/414/files)

**Comment by zelitomas** [comment]
Hello @vaerh,

thanks for the update. I can confirm that import now works both with 
```
terraform import 'module.cap1.routeros_wifi.master["wifi1"]' 'wifi1'
```
and
```
terraform import 'module.cap1.routeros_wifi.master["wifi2"]' 'default_name=wifi2'
```
