### ISSUE TITLE
expose upnp

### ISSUE THREAD

**Issue by rpoovey** [terraform-routeros/terraform-provider-routeros#412]
**Describe the solution you'd like**
Is there any plan to expose `ip/upnp` to Terraform provider? In writing the config for my home router this is the first thing I've stumbled upon that isnt exposed. 

```bash
[admin@MikroTik] > ip/upnp/export
# apr/04/2024 00:48:13 by RouterOS 7.8
# software id = GJYP-LMM3
#
# model = RB5009UG+S+
/ip upnp
set enabled=yes
/ip upnp interfaces
add interface=ether1 type=external
add interface=bridge type=internal
```

**Comment by vaerh** [comment]
Please be patient. I haven't had time to work between ticket closings lately ))))
