### ISSUE TITLE
invalid syntax for 'client_keepalive' field

### ISSUE THREAD

**Issue by blackden** [terraform-routeros/terraform-provider-routeros#432]
**Issue Description:**
When running Terraform planning, an error occurs. The error happens when attempting to create the `routeros_interface_wireguard_peer` resource with the `client_keepalive` parameter. The error indicates that Terraform expects a numeric value for the `client_keepalive` parameter but fails to parse it correctly, even when a numeric value is provided as expected.

**Steps to Reproduce:**
1. Run Terraform using a configuration file that includes the `routeros_interface_wireguard_peer` resource.
2. Attempt to perform planning (`terraform plan`).

**Expected Behavior:**
Expected successful planning execution without errors, as the `client_keepalive` parameter was specified as a numeric value according to the documentation.

**Actual Behavior:**
When performing planning, an error is encountered indicating that Terraform cannot parse the numeric value of the `client_keepalive` parameter, even though it is correctly represented.

**Terraform Version:**
Terraform v1.7.5 
on darwin_arm64

**Configuration File:**
```hcl
resource "routeros_interface_wireguard_peer" "wg_peer" {
  # Other parameters...
  client_keepalive = 25  # Correct numeric value
}
```

**Documentation:**
[Link to the documentation where the `client_keepalive` parameter is described as requiring a numeric value.](https://github.com/terraform-routeros/terraform-provider-routeros/blob/main/docs/resources/interface_wireguard_peer.md#optional)

**Additional Notes:**
```Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: strconv.Atoi: parsing "25s": invalid syntax for 'client_keepalive' field
│ 
│   with routeros_interface_wireguard_peer.wg_peer["0"],
│   on interface_wireguard_peer.tf line 21, in resource "routeros_interface_wireguard_peer" "wg_peer":
│   21: resource "routeros_interface_wireguard_peer" "wg_peer" {
│ 
╵
```

**Comment by vaerh** [comment]
Thanks, fixed!
