### ISSUE TITLE
Missing option /radius service=dot1x (and also ipsec)

### ISSUE THREAD

**Issue by tofkamp** [terraform-routeros/terraform-provider-routeros#440]
**Describe the bug**
In the documentation there is no option for radius service dot1x. Also ipsec service option is missing. I did not test it with a terraform file.

**To Reproduce**
type the following in a terminal on mikrotik (physical?) device:
/radius add service=  (press TAB)

**Expected behavior**
Both options are available.

**Additional context**
![Screenshot 2024-05-02 155559](https://github.com/terraform-routeros/terraform-provider-routeros/assets/11454484/9be151c0-4c3e-4a11-a43e-4b2a7e76e9b5)
Page with explanation how to set dot1x up: https://help.mikrotik.com/docs/display/ROS/Dot1X
Halfway you can find the example command.

**Comment by vaerh** [comment]
Thank you! I have corrected the parameter description. The documentation will be updated after the next release. In any case you can use the current version of the provider, as there is no validation of the value for the current parameter.
