### ISSUE TITLE
import ovpn client config

### ISSUE THREAD

**Issue by tofkamp** [terraform-routeros/terraform-provider-routeros#444]
**Is your feature request related to a problem? Please describe.**
You stated the following challenge:
"This version of the module greatly simplifies the process of adding new resources. You are welcome!"
I am willing to test if I could reprogram my router with terraform.  Most of the config I did was by hand in WinBox. I exported the config to a readable form, and made a real backup also.
I want to upgrade my router, but I do not have a license to upgrade. So I want to wipe the router, install the latest routeros, and then reprogram it with terraform. Then I do not need the upgrade license.
First missing feature I found, is importing an openVPN config file. You can config a server, but my router has a site2site to an other site with other software (not mikrotik), I have the client role.

**Describe the solution you'd like**
/interface/ovpn-client/import-ovpn-configuration file-name=clientconfig.ovpn .....
I do a terraform from my computer, where the config file is. It would be nice to use the file("$path/configfile.ovpn") option in terraform.
A file resource, followed by this command is also a good option.

**Additional context**
Importing the config does a lot of things (certificates, interface, ppp profile, etc). Undoing this config could be tricky.

**Comment by vaerh** [comment]
I'd like to clarify what you want to see in the end? Do you want to add a client resource for OpenVPN or the ability to operate with external configurations via file import?

**Comment by tofkamp** [comment]
No I do not want to import a backup of the device. Just a openvpn client config file import.

**Comment by vaerh** [comment]
Importing, as well as executing some separate commands detached from specific resources, does not fall within the concept of IaC, or maybe within my worldview.
If there is no definition of a resource in the TF script, there is no way to evaluate the correctness of its creation on the router. And most importantly, to track its life cycle.
The only thing I can suggest is to create a new resource for the OpenVPN client.
Another way is to create a resource ```"routeros_file" "openvpn-client" {}``` from TF, import the contents of the file manually on MT, and then import the resource back into TF (after creating ```resource_openvpn_client```).

**Comment by tofkamp** [comment]
Ok, I understand. Mikrotik does not have the openvpn connection as a single structure/object. So IaC is not an option.
I will find an other way. Thank you for clarify this.
