### ISSUE TITLE
LTE interface, APNs

### ISSUE THREAD

**Issue by OJFord** [terraform-routeros/terraform-provider-routeros#464]
I'd like to be able to configure an LTE interface and APN(s).

Probably means new resources:
- `routeros_interface_lte`
- `routeros_interface_lte_apn`

but I haven't really looked into the API yet.

I assume it doesn't exist due to a lack of hardware, I'm adding the issue partly just for the record; I'd be happy to have a look and see about implementing this myself soon hopefully.

**Comment by vaerh** [comment]
@OJFord @suda
Hi!
Can you post the output of the commands from the router that has LTE on it?
```
curl -k -u <admin user> https://<mikrotik>/rest/interface/lte
curl -k -u <admin user> https://<mikrotik>/rest/interface/lte/apn
```

**Comment by OJFord** [comment]
LTE interfaces:
```
[{".id":"*4","allow-roaming":"true","apn-profiles":"default","band":"","comment":"wan","default-name":"lte1","disabled":"false","inactive":"false","mtu":"1500","name":"lte1","network-mode":"3g,lte","running":"true","sms-read":"false"}]
```

(interesting, could've sworn 3G was off!)

APNs:
```
[{".id":"*1","add-default-route":"true","apn":"internet","authentication":"none","comment":"wan","default":"true","default-route-distance":"2","ip-type":"auto","name":"default","passthrough-interface":"ether2","passthrough-mac":"00:00:00:00:00:00","use-network-apn":"true","use-peer-dns":"false"}]
```

**Comment by vaerh** [comment]
Thanks, just what I need!
Can the LTE interface be removed or can it only be disabled?

**Comment by OJFord** [comment]
Only disabled afaict, assuming you mean like loopback and etherN have only the 'D' button, no '-' to remove as some resources (such as if I added an interface) do.

**Comment by vaerh** [comment]
Yeah, that's great. I'll try to implement the standard handlers and you should test them after release. I don't have LTE at all.

**Comment by OJFord** [comment]
Great, thanks, I certainly will 🙂
