### ISSUE TITLE
Naming for Certificate

### ISSUE THREAD

**Issue by durandguru** [terraform-routeros/terraform-provider-routeros#473]
**Is your feature request related to a problem? Please describe.**
Currently there is a routeros_system_certificate and a routeros_certificate_scep_server resource. There are some more options under certificates which are not added yet. Will it be better that both resources follow the system one? So the scep one to rename to routeros_system_certificate_scep_server ?

**Comment by vaerh** [comment]
Resource names are created according to the path to those resources. This makes searching and debugging easier.
If necessary, an alias can be added.

**Comment by vaerh** [comment]
Had another look and yes, you are right! The fixes are in the new release.

**Comment by durandguru** [comment]
Thanks!
