### ISSUE TITLE
Netwatch

### ISSUE THREAD

**Issue by mglants** [terraform-routeros/terraform-provider-routeros#487]
**Is your feature request related to a problem? Please describe.**
Please add netwatch documentation

**Describe the solution you'd like**
As my Providers use google up for checking really want to added it to terraform
**Documentation**
https://help.mikrotik.com/docs/display/ROS/Netwatch

**Comment by vaerh** [comment]
I apologize for such a long response. The resources in the tools section have not been implemented until now and I don't know what problems may arise. For this reason, adding a resource may take longer.
