### ISSUE TITLE
RouterOS 7.x & OSPF Interface Template Auth Key

### ISSUE THREAD

**Issue by bdowne01** [terraform-routeros/terraform-provider-routeros#510]
**Describe the bug**
While importing resources from an existing router, noticed that there was a schema error on the OSPF Interface Template authentication-key param as follows:

`[MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'auth_key': 'xxxxxxxxxx' ◁` 

Digging deeper it seems that at least on our version of RouterOS, the OSPF Interface Template is declared as `auth-key`, not `authentication-key`.   This contradicts Mikrotik's own documentation, here:

 https://help.mikrotik.com/docs/display/ROS/OSPF#OSPF-InterfaceTemplates

Nonetheless, our router running 7.13 (and presumably other 7.x versions) demands it be configured with `auth-key`, as shown:
```
[routeradmin@rtr-01] /routing/ospf/interface-template> /system/resource/print
                   uptime: 21w4d21h16m11s
                  version: 7.13 (stable)
[routeradmin@rtr-01] /routing/ospf/interface-template> set numbers=2
area        auth-key     dead-interval      instance-id     passive         retransmit-interval     use-bfd
auth        comment      disabled           interfaces      prefix-list     transmit-delay          vlink-neighbor-id
auth-id     cost         hello-interval     networks        priority        type                    vlink-transit-area
```

**To Reproduce**
Declare a terraform resource `routeros_routing_ospf_interface_template` that contains an `authentication_key` parameter, attempt to import an existing OSPF Interface Template on a 7.x RouterOS router that has `auth-key` set.

**Expected behavior**
The provider should be able to import the existing auth-key setting from RouterOS 7.x

**Debug Information**
Can provide more data/info/debug if requested.

**Comment by vaerh** [comment]
Thanks, fixed. I couldn't find the exact OS version on which the attribute change occurred. At least since 7.10 the attribute is new, but on 6.48 it is old.

**Comment by bdowne01** [comment]
Hey everyone, reopening this issue.  When we went to try to `apply` a configuration using the latest module version including this fix it seems the provider is still attempting to make REST updates using the wrong nomenclature.  Example:

` │ Error: PATCH 'https://rtr-01/rest/routing/ospf/interface-template/*1' returned response code: 400, message: 'Bad Request', details: 'unknown parameter authentication-key`

**Comment by vaerh** [comment]
Hi! 
Traditionally I need TF_LOG=debug; ROS version, resource section and the answer to the question: is it updating the state of an existing resource or creating a new one.

**Comment by vaerh** [comment]
Hi! 
I need the resource section and the answer to the question: is it updating the state of an existing resource or creating a new one.

**Comment by bdowne01** [comment]
We're attempting to update an existing one that was imported (same resource as above).

Here's the delcaration:
`resource "routeros_routing_ospf_interface_template" "bh_template" {
  for_each           = var.backhaul_interfaces
  area               = format("%s-%s", lower(lookup(local.ospf_area_db[each.value.ospf_area], "name", "tower")), "area")
  auth               = "md5"
  auth_id            = 1
  authentication_key = each.value.ospf_auth
  cost               = floor(var.ospf_default_cost / each.value.uplink_megabits)
  interfaces         = toset([format("%s-%s-%s-%s", each.key, lower(var.tower_code), lower(each.value.peer), "xc")])
  type               = "ptp"
  comment            = "Backhaul link to ${each.value.peer}"
}`

However, I just noticed the documentation for the new version that we should now be specifying `auth_key` instead, so I'm sure that's it.   When we can test it next I'll update the issue.

**Comment by bdowne01** [comment]
Yep, that was the problem.  Switched the argument over to `auth_key` and we're all good.  Ty again!
