### ISSUE TITLE
Schema Error on SFP Ports

### ISSUE THREAD

**Issue by bdowne01** [terraform-routeros/terraform-provider-routeros#514]
**Describe the bug**
Ran into bug with schema when importing a `routeros_interface_ethernet` resource from a physical SFP ethernet port on an existing router running RouterOS 7.13:

`[MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'fec_mode': 'auto' ◁`

According to the RouterOS documentation this parameter exists on SFP ports for the purpose of compatibility for SFP28, QSFP+ and QSFP28 interfaces:
https://help.mikrotik.com/docs/display/ROS/Ethernet

We're running this provider against a RB4011iGS+5HacQ2HnD, which only has a SFP+ 10gig port, so presumably this should fix any import errors on models with any type of ethernet SFP port.

**To Reproduce**
Attempt to import an `routeros_interface_ethernet` resource on an existing SFP ethernet port

**Expected behavior**
The resource should import without schema errors.

**Debug Information**
Can provide more if requested.

**Comment by bdowne01** [comment]
Also thank you for the uber-fast fix on the prior issue!

**Comment by vaerh** [comment]
You're welcome!

If the attribute is not urgently needed, I will add it along with other additions in the coming days.
