### ISSUE TITLE
Deleting routeros_ip_firewall_filter.in_interface tries to PATCH.

### ISSUE THREAD

**Issue by bdowne01** [terraform-routeros/terraform-provider-routeros#521]
**Describe the bug**
When testing the provider against RouterOS 7.13, `routeros_ip_firewall_filter` cannot remove an `in_interface` value previously configured.  Attempting to do so results in the provider attempting to `PATCH` the API with a 'null' value, which returns an HTTP 400 error claiming the 'null' string is ambiguous:

```
terraform plan
  # module.test.routeros_ip_firewall_filter.allow_traffic will be updated in-place:
  ~ resource "routeros_ip_firewall_filter" "allow_traffic" {
        id                = "*A"
      - in_interface      = "ether1" -> null
    }

terraform apply
module.test.routeros_ip_firewall_filter.allow_traffic: Modifying... [id=*A]
╷
│ Error: PATCH 'https://rtr-01/rest/ip/firewall/filter/*A' returned response code: 400, message: 'Bad Request', details: 'ambiguous value of interface, more than one possible value matches input'
```
I believe this is because it is attempting to set the value of the `in_interface` string to `null` versus removing the value altogether.

**To Reproduce**

1. Create an `ip_firewall_filter` resource with `in_interface` set:
```
resource "routeros_ip_firewall_filter" "allow_traffic" {
  comment           = "Permits some traffic"
  chain             = "input"
  action            = "accept"
  protocol          = "tcp"
  dst_port          = "80"
  in_interface = "ether1"
}
```
2. Apply this configuration (succeeds)
3. Attempt to modify the resource by removing the `in_interface`
```
resource "routeros_ip_firewall_filter" "allow_traffic" {
  comment           = "Permits some traffic"
  chain             = "input"
  action            = "accept"
  protocol          = "tcp"
  dst_port          = "80"
  in_interface_list = "http-interfaces"
}
```

**Expected behavior**
The modification should succeed without error.

**Additional context**
This problem can be worked around by going directly on to the Mikrotik and removing the `in_interface` attribute with 'unset', before running the terraform plan/apply for example:

`unset numbers=0 in-interface` 

The REST API documentation doesn't specify how `unset` should be called via API.   HTTP DELETE operations remove entire table records, and HTTP PATCH only runs `set`.   Not sure this is fixable at the moment.
https://help.mikrotik.com/docs/display/ROS/REST+API

**Comment by vaerh** [comment]
Changed it, but this can happen with other attributes. So check it and if there will be problems, write me.
