### ISSUE TITLE
resource for user public ssh key

### ISSUE THREAD

**Issue by Schwitzd** [terraform-routeros/terraform-provider-routeros#527]
**Is your feature request related to a problem? Please describe.**
Would be great to have a resource to import an ssh public key for a specific user

**Describe the solution you'd like**
add a resources named something like routeros_system_user_sshkey

**Documentation**
N/A

**Additional context**
N/A

**Comment by vaerh** [comment]
@Schwitzd 
Hi!
I tried to implement your request but encountered a problem. It is not possible to identify SSH keys belonging to the same user on the MT side. There is no fingerprint of them, which would be logical.
Without this it is not possible to implement the requested resource.
If you have time and energy, try to write to MT with a request to add the fingerprint field to the key output.
P.S. The same problem is typical for importing private keys.

![image](https://github.com/user-attachments/assets/f876d603-2ff5-4d27-b7ea-090c57975284)


![image](https://github.com/user-attachments/assets/683624a3-2a0f-4f94-afa8-be407f058a93)

**Comment by Schwitzd** [comment]
Ciao vaerh,

I realised I wrote my request really badly, my goal is to add an ssh public/private key for a user.

something you will do from terminal with the command 
/user/ssh-keys import bla bla bla

With Terraform I have in mind something like:

   1. generate the key with "tls_private_key"
   1. write to disk the private key with "local_sensitive_file"
   1. upload the key with "routeros_file"
   1. associate the uploaded key to the user with this new resource


Managing an existing user-associated ssh key with Terraform may also be of interest to someone, but this may lead to some security issues (at least for private keys).

**Comment by vaerh** [comment]
I probably didn't describe the problem well. I'll try to do it again. 
Importing any settings cannot be done without creating some resource. So if we want to import a public key and attach it to a user, we need to create a resource first. 
The resource is needed for the TF to have an object to operate on, this is the concept of the TF. 
When creating a resource, the API command is executed and the object is checked if it was successfully created. The check is performed by a unique identifier. So the problem with importing the key is that there seems to be no external parameter to distinguish similar records, as I mentioned above. In this case it is impossible to create a resource on the TF side. 

I will check one hypothesis a little later, but it is unlikely that it will help.

**Comment by Schwitzd** [comment]
ahhhhhh sorry!! now I got the point!
According to your print screens every ssh key has a unique identifier (first column) when you are importing the key the API is not returning this unique identifier?

**Comment by vaerh** [comment]
Unfortunately MT returns an empty response after importing.

**Comment by Schwitzd** [comment]
Uffff I dreamed for a bit.. Do you know the best way to create a feature request to MT?

**Comment by vaerh** [comment]
If I understand correctly, the main tool is their forum. My email to tech support went unanswered.

**Comment by Schwitzd** [comment]
Ok I have implemented my own solution as a workaround..

1. I created a module to generate ssh keys
1. Uploaded the public key with "routeros_file"
1. Based on the documentation ssh password based authentication is allow only if the user has no public key associated, so I use "local-exec" to associate the uploaded public key with the user (downside is that Terraform is prompting for the ssh password)

```hcl
# Generate SSH keys for admin user
module "sshkey_admin" {
  source = "git::https://github.com/Schwitzd/terraform-modules.git//ssh-keygen"

  algorithm     = "ED25519"
  keys_name     = local.dns_records[0].hostname
  write_to_file = true
}

resource "routeros_file" "ssh_publickey_admin" {
  name     = basename(module.sshkey_admin.public_key_filename)
  contents = module.sshkey_admin.public_key
}

resource "null_resource" "import_publickey_admin" {
  provisioner "local-exec" {
      command = <<EOT
        ssh ${local.router_user}@${var.router_ip} '/user/ssh-keys import user=${local.router_user}  public-key-file=${routeros_file.ssh_publickey_admin.name} key-owner=${local.router_user}'
      EOT
  }

  depends_on = [ routeros_file.ssh_publickey_admin ]
}
```
