### ISSUE TITLE
routeros_interface_ethernet_switch_port: multiple field missing in the schema

### ISSUE THREAD

**Issue by kkerssem** [terraform-routeros/terraform-provider-routeros#538]
╷
│ Warning: Field 'rx_jabber' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'rx_jabber': '0' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_65_127' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_65_127': '122699042' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_512_1023' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_512_1023': '14388325' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'mirror_ingress' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'mirror_ingress': 'false' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'mirror_ingress_target' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'mirror_ingress_target': 'none' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'rx_unicast' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'rx_unicast': '124635824' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_fcs_error' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_fcs_error': '0' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_128_255' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_128_255': '62395699' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'mirror_egress' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'mirror_egress': 'false' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'running' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'running': 'true' ◁
│ 
│ (and 8 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_unicast' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_unicast': '498792187' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_1024_max' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_1024_max': '178834558' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_256_511' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_256_511': '238821535' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'rx_error_events' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'rx_error_events': '0' ◁
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Field 'tx_rx_64' not found in the schema
│ 
│   with routeros_interface_ethernet_switch_port.ether1,
│   on main.tf line 461, in resource "routeros_interface_ethernet_switch_port" "ether1":
│  461: resource "routeros_interface_ethernet_switch_port" "ether1" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_64': '18459026' ◁
│ 
│ (and 9 more similar warnings elsewhere)

**Additional context**
RB5009UG+S+IN running 7.15.2

**Comment by vaerh** [comment]
Thank you, fixed.
