### ISSUE TITLE
routeros_wifi keeps detecting changes

### ISSUE THREAD

**Issue by Schwitzd** [terraform-routeros/terraform-provider-routeros#552]
**Describe the bug**
Since I added `Security.management-encryption` to `routeros_wifi` on each apply, Terraform tries to apply the change again.

**To Reproduce**
This is my code:

```
resource "routeros_wifi" "network_wifi" {
  for_each = local.wifi_settings

  arp_timeout = each.value.arp_timeout
  channel = {
    band                = lookup(each.value, "band", null)
    frequency           = lookup(each.value, "frequency", null)
    reselect_interval   = each.value.reselect_interval
    secondary_frequency = lookup(each.value, "secondary_frequency", null)
    skip_dfs_channels   = "10min-cac"
    width               = lookup(each.value, "width", null)
  }
  configuration = {
    mode    = "ap"
    ssid    = each.value.ssid
  }
  datapath = {
    vlan_id = each.value.vlan_id
  }
  disabled    = false
  l2mtu       = 1560
  mac_address = each.value.mac_address
  name        = each.value.name
  security = {
    authentication_types  = each.value.authentication_types
    connect_priority      = "0"
    ft                    = "true"
    ft_over_ds            = "true"
    passphrase            = each.value.passphrase_key
    management-encryption = each.value.management_encryption
    management_protection = each.value.management_protection
    wps                   = "disable"
  }
}
```

**Expected behavior**
I'm expecting that the change is applied only one time.

**Debug Information**
N/A

**Stack Trace**
N/A

**Additional context**
N/A

**Comment by vaerh** [comment]
What caught my eye is that the attribute name has a dash instead of an underscore. But I can't tell without my PC if that's the cause. 
I'll take a look, but probably closer to Monday.

**Comment by Schwitzd** [comment]
my fault... is with underscore... but should not return an error?

**Comment by vaerh** [comment]
I was just thinking the same thing. We should try to add a validator, since such errors have already occurred.

**Comment by Schwitzd** [comment]
Would be really great :)
Unfortunately I have no knowledge  about go language :'(

**Comment by vaerh** [comment]
It's never too late to start enjoying syntactic sugar :) 
And seriously, I need to see if I can add such a check and where to do it properly. So this is not the only resource with such attributes.
