### ISSUE TITLE
dns ad list support

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#554]
routeros V7.15 introduce the support of dns ad list. We can now block ads directly at router level.

That would be great to be able to set it up with terraform

**Comment by vaerh** [comment]
Hey! I'm in.

**Comment by Schwitzd** [comment]
why not routeros_ip_dns_adlist?

**Comment by vaerh** [comment]
Probably because I'm a little tired. Thanks, I'll fix it!
