### ISSUE TITLE
hotspot support?

### ISSUE THREAD

**Issue by jmuchovej** [terraform-routeros/terraform-provider-routeros#555]
**Is your feature request related to a problem? Please describe.**
I'm trying to document my [home] network infrastructure to avoid config amnesia. Currently, I'm trying to setup HotSpot (lol. overkill, maybe, but bear with me 😅) – but the only way to do this is through WebFig/WinBox (or the terminal).

**Describe the solution you'd like**
It seems like the REST API supports `ip/hotspot` – so I'm curious if it would be possible to support it within the provider.

**Documentation**
- [HotSpot docs](https://help.mikrotik.com/docs/pages/viewpage.action?pageId=56459266)
- [HotSpot customization](https://help.mikrotik.com/docs/display/ROS/Hotspot+customisation)

**Additional context**
While I'm a novice at Go and Terraform Providers – I think I could carve out some time to submit a PR for this, if that would increase its chances of getting integrated.

**Comment by vaerh** [comment]
I can't guarantee yet that it will be possible to add such a resource. I need to see what REST commands are used to implement it.
