### ISSUE TITLE
power over ethernet (POE)

### ISSUE THREAD

**Issue by tofkamp** [terraform-routeros/terraform-provider-routeros#585]
**Is your feature request related to a problem? Please describe.**
My company bought 10 switches with POE, and now I want to manage them, but I could not find the Power Over Ethernet commands

**Describe the solution you'd like**
Have a resource for control, and maybe a datasource of a POE interface

**Documentation**
(https://help.mikrotik.com/docs/display/ROS/PoE-Out)

**Additional context**
This is not so common.  If you don't have access to a POE switch, I can give you some sample data.

**Comment by durandguru** [comment]
You can already define POE settings on interfaces. See https://registry.terraform.io/providers/terraform-routeros/routeros/latest/docs/resources/interface_ethernet I use this to enable/disable POE on an interface. Is there something else missing?

**Comment by vaerh** [comment]
@durandguru Thanks, I was going to answer the same thing!

@tofkamp Can you please tell me what you expect to see in the data source?

**Comment by tofkamp** [comment]
Thank you for pointing that out. I will use that.

For the datasource, you might be able to get the voltage, current and power. I think the power is the most important one. With this datasource, we could detect if something is connected (using power), and then config it in a way.
On the webpage I provided, you can find the term "poe-out-voltage". If it is difficult to implement, don't bother.

**Comment by vaerh** [comment]
Perhaps it makes sense to create a data source with a single field that specifies whether or not there is power consumption?

**Comment by tofkamp** [comment]
You could, but I solved it with another solution.
You can close this issue.
