### ISSUE TITLE
warning  Field 'revision' not found in the schema in routeros_system_routerboard datasource

### ISSUE THREAD

**Issue by tofkamp** [terraform-routeros/terraform-provider-routeros#602]
**Describe the bug**
When I use the datasource I get the warning:
│ Warning: Field 'revision' not found in the schema
│
│ with module.mikrotik_xxxx.data.routeros_system_routerboard.data,
│ on mikrotik\main.tf line 347, in data "routeros_system_routerboard" "data":
│ 347: data "routeros_system_routerboard" "data" {}
│
│ [MikrotikResourceDataToTerraformDatasource] the field was lost during the Schema development: ▷ 'revision': 'r2' ◁
│

**To Reproduce**
data "routeros_system_routerboard" "data" {}

**Expected behavior**
Have the field revision available in the datasource, and no warning

**Debug Information**
See #588 for json data of the output

**Additional context**
Example code to show the version and hardware of the switch. It would be nice to also have the revision of the routerboard.

############# Report type and version ###########
data "routeros_system_resource" "data" {}
data "routeros_system_routerboard" "data" {}

output "architecture_name" {
  value = data.routeros_system_resource.data.architecture_name
}

output "version" {
  value = "${data.routeros_system_resource.data.version} ${data.routeros_system_routerboard.data.current_firmware}"
}
output "board_name" {
  value = "${data.routeros_system_resource.data.board_name} ${data.routeros_system_routerboard.data.serial_number}"
}

**Comment by vaerh** [comment]
Yes, I apologize! It's my mistake. Fixed it, check it after the release.
