### ISSUE TITLE
Support for /interface/wireless/connect-list

### ISSUE THREAD

**Issue by xelite** [terraform-routeros/terraform-provider-routeros#605]
Please create resource `routeros_interface_wireless_connect_list` for support command  `/interface/wireless/connect-list`.

**Comment by vaerh** [comment]
Hi!
After the release I ask to check the resource, as my hardware doesn't support Wave2 and I have no place to test the correctness of it.

**Comment by xelite** [comment]
Hi,
I tested the resource. I was able to create, modify, delete, and import. However, I received warnings. Below is a list of all that occurred:
```
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_uesa': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_hotspot20': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_hotspot20_dgaf': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_network_type': 'wildcard' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_venue': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_roaming_ois': '' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_ipv6_availability': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_hessid': '00:00:00:00:00:00' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_internet': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_asra': 'any' ◁
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'iw_esr': 'any' ◁
```

![image](https://github.com/user-attachments/assets/f2f406cd-612a-4b0a-b045-4c8e90aad113)

**Comment by vaerh** [comment]
I saw 15 `iw-` attributes in the console, but couldn't find any information about them. Maybe you can give me a hint?
https://github.com/terraform-routeros/terraform-provider-routeros/blob/82305a2407e6493d2f307318dc4ab2cf763ce470/routeros/resource_interface_wireless_connect_list.go#L49-L53

**Comment by xelite** [comment]
I don'n know what it is. This is how resorce created with terraform looks from winbox:
```
[admin@sxt-mostowa] > /interface/wireless/connect-list/print 
Flags: X - disabled 
 0 X interface=wlan1 connect=yes mac-address=00:00:00:00:00:00 ssid="xsdsdsd" signal-range=-120..120 allow-signal-out-of-range=10s area-prefix="" security-profile=default wireless-protocol=any interworking=any iw-network-type=wildcard iw-venue=any 
     iw-hessid=00:00:00:00:00:00 iw-internet=any iw-asra=any iw-esr=any iw-uesa=any iw-hotspot20=any iw-hotspot20-dgaf=any iw-roaming-ois="" iw-ipv4-availability=any iw-ipv6-availability=any 3gpp="" 
```

I can't set iw-* from ui:
![image](https://github.com/user-attachments/assets/fd2dc561-8f6b-45a8-92f8-6b1e0dd3db8a)

Maybe set up default values like above with optional change in resource provider?

**Comment by vaerh** [comment]
<details><summary>Details</summary>
<p>
iw-asra= any     no     yes
iw-authentication-types= dns-redirection     https-redirection     online-enrollment     terms-and-conditions
iw-connection-capabilities=
iw-esr= any     no     yes
iw-hessid=
iw-hotspot20= any     no     yes
iw-hotspot20-dgaf= any     no     yes
iw-internet= any     no     yes
iw-ipv4-availability= any     double-nated     not-available     port-restricted     port-restricted-double-nated     port-restricted-single-nated     public     single-nated     unknown
iw-ipv6-availability= any     available     not-available     unknown
iw-network-type= emergency-only     personal-device     private     private-with-guest     public-chargeable     public-free     test     wildcard
iw-realms=
iw-roaming-ois=
iw-uesa= any     no     yes
iw-venue=......
any              business           industrial                 institutional         mercantile-...     residential         storage-unspecified     vehicular       
assembly         business-...       industrial-factory         institutional-...     outdoor            residential-...     utility                 vehicular-...   
assembly-...     educational...     industrial-unspecified     mercantile            outdoor-...        storage             utility-unspecified     
</p>
</details>
