### ISSUE TITLE
Using `5ghz-an` for `routeros_wifi_channel` returns status code `400`

### ISSUE THREAD

**Issue by Scandiravian** [terraform-routeros/terraform-provider-routeros#619]
**Describe the bug**
When setting a wifi channel to `5ghz-an` the rest api returns the error `returned response code: 400, message: 'Bad Request', details: 'input does not match any value of band'`

**To Reproduce**
Configure a wifI channel to use `5ghz-an` and apply it

**Expected behavior**
It should be possible to configure a 5GHz channel to use the `A/N` band. The correct name in the rest api is `5ghz-n`, but this does not pass validation from the provider

**Debug Information**
Not relevant

**Stack Trace**
Not relevant

**Additional context**
AP is a Cap AX running RouterOS version 7.16.2

**Comment by vaerh** [comment]
Hi, I added the correct parameter to the validator without removing the old one. I don't know if it was even on previous versions of ROS.
