### ISSUE TITLE
Missing field in interface_bridge_filter

### ISSUE THREAD

**Issue by prototux** [terraform-routeros/terraform-provider-routeros#620]
**Describe the bug**
The interface_bridge_filter is missing the "passthrough" field (this seems to be a boolean)

**To Reproduce**
Define/import a routeros_interface_bridge_filter resource on routeros 7.16.1, i don't know since when this field exist in routeros sadly.

**Debug Information**
[MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'passthrough': 'true' ◁

**Comment by vaerh** [comment]
Thank you so much for your help!

**Comment by prototux** [comment]
@vaerh thanks! :)
