### ISSUE TITLE
Multi-passphrase wifi security

### ISSUE THREAD

**Issue by holmesb** [terraform-routeros/terraform-provider-routeros#621]
Hi,

`/interface/wifi/security/multi-passphrase/` landed a few betas ago and has reached the [docs](https://help.mikrotik.com/docs/spaces/ROS/pages/224559120/WiFi#WiFi-Securitymulti-passphraseproperties). Will prob be in a stable release within a month or so.

Allows using a different password to connect to the same WiFi, and you can specify VLAN for each password. Super cool! WPA2 will be with us for the foreseeable, and this massively improves its security, without going to the effort of implementing a RADIUS server.

Be great to include in this provider.

**Comment by vaerh** [comment]
No problem. Once out - test and come back with feedback.
