### ISSUE TITLE
Ability for create containers

### ISSUE THREAD

**Issue by metajiji** [terraform-routeros/terraform-provider-routeros#86]
**Is your feature request related to a problem? Please describe.**
A container is MikroTik's implementation of Linux containers, allowing users to run containerized environments within RouterOS. For example run traefik would be very useful!

**Describe the solution you'd like**
Manage lifecycle for containers, env variables, versions, etc.

**Additional context**
Here oficial guide for create container
https://help.mikrotik.com/docs/display/ROS/Container

**Comment by GNewbury1** [comment]
Hmm, the difficulty I'm having with this is the automated testing. There are a few things here:

- Containers need a package installed. To install a package, you need to upload an `npk` file, which can't be done with the CLI.
- Assuming you can get the package installed, you still need to enable the feature. This involves running `/system/device-mode/update container=yes`, which is fine, but then it requires forcibly shutting down RouterOS (simulate a power loss, for example).

I think we might have to wait until we can either commit a fair bit of time to figuring out the above two problems, or if/when Mikrotik make the feature more accessible via the command line/api.

**Comment by vaerh** [comment]
It seems to me that we can skip the moment of enabling containerization, since routers are initially preconfigured anyway.

**Comment by vaerh** [comment]
Yes, I experimented a bit. Automatic docker package installation is a big problem.

**Comment by vaerh** [comment]
#356 
[Released](https://github.com/terraform-routeros/terraform-provider-routeros/releases/tag/v1.33.1)
